import React, { Component } from "react"

class markup extends Component {
  state = {}

  render() {
    return (

      <section className="page markup">
        <div className="container">
          <div className="row">
            <div className="col-xs-12">

              <div className="markup-synapse-card">
                start ljubo's new html


              <div class="portalCard typeStudy layoutLandscape showMetadata">
                  <div class="cardThumbnail">
                    <img alt="" src="/static/media/study-complete.b012f80b.svg" />
                    <div>Active</div>
                  </div>
                  <div class="cardContent">
                    <div class="type">Study</div>
                    <div class="title"><h3><a>DHART SPORE Project 4: Subsequent Malignant Neoplasms (SMNs) Among NF1 Cancer Survivors.</a></h3></div>
                    <div class="author">Smita Bhatia / Jean L. Nakamuralue</div>
                    <div class="description">
                      Subsequent malignant neoplasms (SMNs) are histologically distinct cancers that develop months to years
                      after patients receive radiation and/or chemotherapy to cure a primary malignancy. SMNs are a
                      fundamental problem in cancer survivors. Compelling data generated by Drs. Nakamura and Shannon in GEM
                      mice demonstrated that irradiation cooperates strongly with heterozygous Nf1 inactivation in the
                      development of a spectrum of SMNs that recapitulate common SMNs in human patients with and without NF1.
                      Project 4 will translate these novel data and will systematically assess the incidence of SMNs in NF1
                      patients and examine associated risk factors such as age at diagnosis, anatomic site of the primary
                      tumor, and dose and duration of prior treatment. Data compiled by the NCI-funded Childhood Cancer
                      Survivor Study (CCSS) will play an integral role in Project 4. The aims of Project 4 are: Aim 1. To
                      describe the magnitude of risk of second malignant neoplasms (SMNs) in individuals with NF1. Aim 2. To
                      perform comparative oncogenomics to identify genetic alterations associated with radiation-induced
                      tumorigenesis in individuals with NF1. Aim 3. To validate in model systems the biologic importance of
                      candidate pathways in radiation-induced tumorigenesis and to determine whether radiotherapy promotes
                      transformation of plexiform neurofibromas to MPNSTs in vivo. The translational impact of this work
                      involves informing current clinical practice in the treatment of tumors arising in NF1 patients to
                      reduce the risk of SMN, and generating insights into the underlying biology of SMN that will lead to
                      new therapies for these common, aggressive, and largely refractory cancers.
                      </div>
                    <div class="cardAnnotations">
                      <span>Neurofibromatosis 1</span>
                      <span>Cutaneous Neurofibroma</span>
                    </div>
                  </div>

                  <div class="cardMetadata">
                    <div class="row">
                      <div class="row-label">Status</div>
                      <div class="row-data">Active</div>
                    </div>
                    <div class="row">
                      <div class="row-label">Funder</div>
                      <div class="row-data"><a>NTAP</a></div>
                    </div>
                    <div class="row">
                      <div class="row-label">Data</div>
                      <div class="row-data">Under embargo</div>
                    </div>
                    <div class="row">
                      <div class="row-label">Publications</div>
                      <div class="row-data"><a>Some publication title</a></div>
                    </div>
                  </div>
                </div>



                <div class="portalCard typeDataset layoutLandscape showMetadata">

                  <div class="cardThumbnail">
                    <img alt="" src="/static/media/Data2.1104e430.svg" />
                    <div>353Kb</div>
                  </div>
                  <div class="cardContent">
                    <div class="type">Dataset</div>
                    <div class="title"><h3><a>SYNODOS NF2 DRUG SCREENING (RAW AND PROCESSED)</a></h3></div>
                    <div class="description">
                      This set contains raw and processed drug screening data for NF2 schwannoma and meningioma models generated that were tested with a panel of 19 experimental therapeutics and drugs.
      </div>
                    <div class="cardAnnotations">
                      <span>Neurofibromatosis 2</span>
                      <span>Schwannoma, Meningioma</span>
                    </div>

                  </div>
                  <div class="cardAction">
                    <button type="button">Download Dataset</button>
                  </div>

                  <div class="cardMetadata">
                    <div class="row">
                      <div class="row-label">Funder</div>
                      <div class="row-data"><a>NTAP</a></div>
                    </div>
                    <div class="row">
                      <div class="row-label">Size</div>
                      <div class="row-data">343 KB</div>
                    </div>
                    <div class="row">
                      <div class="row-label">Files</div>
                      <div class="row-data">3</div>
                    </div>
                  </div>
                </div>




                <div class="portalCard typePublication layoutLandscape showMetadata">


                  <div class="cardThumbnail">
                    <img alt="" src="/static/media/Publication.b630024c.svg" />
                  </div>
                  <div class="cardContent">
                    <div class="type">Publication</div>
                    <div class="title"><h3><a>ANGUS SP, ET AL. EPH RECEPTOR SIGNALING AS A NOVEL THERAPEUTIC TARGET IN NF2-DEFICIENT MENINGIOMA. NEURO ONCOL (2018).</a></h3></div>
                    <div class="author">Smita Bhatia / Jean L. Nakamuralue</div>
                    <div class="cardAnnotations">
                      <span>Neurofibromatosis 2</span>
                      <span>Schwannoma, Meningioma</span>
                    </div>
                  </div>

                  <div class="cardMetadata">
                    <div class="row">
                      <div class="row-label">Funder</div>
                      <div class="row-data"><a>NTAP</a></div>
                    </div>
                    <div class="row">
                      <div class="row-label">DOI</div>
                      <div class="row-data"><a>10.1093/neuonc/noy046</a></div>
                    </div>
                    <div class="row">
                      <div class="row-label">Study</div>
                      <div class="row-data"><a>Synodos NF2</a></div>
                    </div>
                  </div>
                </div>



                <div class="portalCard typeTool layoutLandscape">
                  <div class="cardThumbnail">
                    <img alt="" src="/static/media/DNA_Two.d8f80972.svg" />
                  </div>
                  <div class="cardContent">
                    <div class="type">Tool</div>
                    <div class="title"><h3><a>DRUG-TARGET EXPLORER</a></h3></div>
                    <div class="description">
                      Identify drugs that target your gene of interest, genes that are affected by your compound, or pharmacologically similar compounds.
                    </div>
                  </div>
                  <div class="cardAction">
                      <button type="button">Open Tool</button>
                    </div>
                </div>



                <div class="portalCard typeFunder layoutLandscape">
                  <div class="cardThumbnail">
                    <img class="logo" src="https://www.ctf.org/assets/img/childrens-tumor-foundation.png" />
                  </div>
                  <div class="cardContent">
                    <div class="type">Funder</div>
                    <div class="title"><h3><a>Children Cancer Foundation</a></h3></div>
                    <div class="website"><a>www.ctf.org</a></div>
                    <div class="description">
                      Founded in 1978, the Children's Tumor Foundation (CTF) began as the first grassroots organization solely dedicated to finding treatments for neurofibromatosis (NF). Today, CTF is a widely recognized national nonprofit foundation, a leading force in the fight to end NF, and a model for other innovative research endeavors. CTF has partnered with Sage Bionetworks to create a pan-NF data portal available for NF researchers and other stakeholders. The portal contains molecular and clinical data coming from the many projects that the Foundation is managing. In particular, the Synodos consortia projects will use platforms built by Sage Bionetworks to execute their data analysis and integration, releasing their datasets in a timely fashion. The Synodos projects work with a 12-month embargo on data release, allowing their participants to share results in real-time within an exclusive space, and then releasing them after the confidentiality period. Many other projects that the Foundation is managing and sponsoring will also use this platform as a resource for making data available for the research community. The data being generated by CTF-funded projects include drug screening datasets, genomic characterization of model systems, multiplexed analysis, and several other publicly available datasets.
                      </div>
                  </div>
                  <div class="cardAction">
                    <button type="button">View Funded Research</button>
                  </div>

                </div>


                end ljubo's new html
              </div>

            </div>
          </div>
        </div>
      </section>

    )
  }
}

export default markup
