#!/bin/bash

# update the data
cd nf-portal-server/src
node index.js
cd ../../
# update s3
echo "pushing local to staging"
aws s3 sync --delete --cache-control max-age=0 ./build s3://staging.nf.synapse.org
