Object.defineProperty(exports, "__esModule", {
  value: true,
})
/** QueryBundleRequest constants */
const BUNDLE_MASK_QUERY_RESULTS = (exports.BUNDLE_MASK_QUERY_RESULTS = 1)
const BUNDLE_MASK_QUERY_COUNT = (exports.BUNDLE_MASK_QUERY_COUNT = 2)
const BUNDLE_MASK_QUERY_SELECT_COLUMNS = (exports.BUNDLE_MASK_QUERY_SELECT_COLUMNS = 4)
const BUNDLE_MASK_QUERY_MAX_ROWS_PER_PAGE = (exports.BUNDLE_MASK_QUERY_MAX_ROWS_PER_PAGE = 8)
const BUNDLE_MASK_QUERY_COLUMN_MODELS = (exports.BUNDLE_MASK_QUERY_COLUMN_MODELS = 16)
const BUNDLE_MASK_QUERY_FACETS = (exports.BUNDLE_MASK_QUERY_FACETS = 32)

module.exports = {
  BUNDLE_MASK_QUERY_RESULTS,
  BUNDLE_MASK_QUERY_COUNT,
  BUNDLE_MASK_QUERY_MAX_ROWS_PER_PAGE,
  BUNDLE_MASK_QUERY_COLUMN_MODELS,
  BUNDLE_MASK_QUERY_FACETS,
  BUNDLE_MASK_QUERY_SELECT_COLUMNS,
}
