const study = {
  diseases: { count: 0, facetValues: [] },
  assay: { count: 0, facetValues: [] },
  tissue: { count: 0, facetValues: [] },
  analysisType: { count: 0, facetValues: [] },
  cellType: { count: 0, facetValues: [] },
  consortium: { count: 0, facetValues: [] },
  grant: { count: 0, facetValues: [] },
  isConsortiumAnalysis: { count: 0, facetValues: [] },
  isModelSystem: { count: 0, facetValues: [] },
  species: { count: 0, facetValues: [] },
  dataType: { count: 0, facetValues: [] },
  dataSubtype: { count: 0, facetValues: [] },
  assayTarget: { count: 0, facetValues: [] },
  organ: { count: 0, facetValues: [] },
  celltype: { count: 0, facetValues: [] },
  isMultiSpecimen: { count: 0, facetValues: [] },
  fileFormat: { count: 0, facetValues: [] },
}
export default study
